apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rahul-node
  name: rahul-node-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: rahul-node
  type: LoadBalancer
status:
  loadBalancer: {}
