apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: task-mongo
  name: db-lb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: task-mongo
status:
  loadBalancer: {}
