apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rahul-deploy1
  name: rahul-web-extenal-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rahul-deploy1
  type: LoadBalancer
status:
  loadBalancer: {}
